name: Java CI with Maven

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: "zulu"
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --no-transfer-progress
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: CatSeedLogin
          path: |
            target/*.jar
